version: '3'
services:
    bkadmin:
        image: nexusserver:8082/fw-admin-server:0.0.74
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - bkconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2048M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - bkadmin
        ports:
            - "6001:6001"
        environment:
            SPRING_PROFILES_ACTIVE: prod
            EUREKA_INSTANCE_HOSTNAME: bkadmin
            SERVER_PORT: 6001
            DEVLOPER_NAME: ""
            spring.config.location: "file:/home/DockerCommand/default/"
            APPLICATION_NAME: admin
    bkturbine:
        image: nexusserver:8082/fw-turbine-server:0.0.74
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - bkconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2048M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
        networks:
            docker-net:
                aliases:
                    - bkturbine
        ports:
            - "6021:8080"
        environment:
            SPRING_PROFILES_ACTIVE: prod
            EUREKA_INSTANCE_HOSTNAME: bkturbine
            DEVLOPER_NAME: ""
            spring.config.location: "file:/home/DockerCommand/default/"
            APPLICATION_NAME: turbine
networks:
    docker-net:
        external:
            name: docker-net