version: '3'
services:
    bk-logcent:
        image: nexusserver:8082/fw-logcent:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 1024M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
                mem_swappines: 0
        networks:
            docker-net:
                aliases:
                    - p2p-logcent
        ports:
            - "6011:6011"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SERVER_PORT=6011
            - DEVLOPER_NAME=dev
    bkadmin:
        image: nexusserver:8082/fw-admin-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - bkconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 2046M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
                mem_swappines: 0
        networks:
            docker-net:
                aliases:
                    - bkadmin
        ports:
            - "6001:6001"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - HOSTNAME=bkadmin
            - SERVER_PORT=6001
            - DEVLOPER_NAME=dev
    bkturbine:
        image: nexusserver:8082/fw-turbine-server:latest
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        depends_on:
            - bkconfig
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 1024M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
                mem_swappines: 0
        networks:
            docker-net:
                aliases:
                    - bkturbine
        ports:
            - "6021:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - EUREKA_INSTANCE_HOSTNAME=bkturbine
            - DEVLOPER_NAME=dev
networks:
    docker-net:
        external:
            name: docker-net