version: '3'
services:
    bkzuul:
        image: nexusserver:8082/fw-zuul-server:0.0.70
        volumes:
            - /home/DockerCommand/:/home/DockerCommand/
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    #cpus: '0.001'
                    memory: 3072M
                reservations:
                    #cpus: '0.0001'
                    memory: 64M
                #mem_swappines: 0
        networks:
            - docker-net
        ports:
            - "5001:5001"
        environment:
            SPRING_PROFILES_ACTIVE: prod
            bk.onServer.enabled: "true"
            spring.config.location: "file:/home/DockerCommand/default/"
            APPLICATION_NAME: zuul
            DEVLOPER_NAME: "-bank0001""
            #BK_LOGSTASH_URL: "10.29.197.202:4560"
networks:
    docker-net:
        external:
            name: docker-net
