#--server.port=9090 --spring.profiles.active=dev,--eureka.instance.hostname=configserver2
HOSTNAME: ${spring.cloud.client.ipAddress}
---
spring:
    profiles: dev
    rabbitmq:
        host: 192.168.10.18
        port: 5672
        username: user_admin
        password: admin123%
...

---
spring:
    profiles: test
    rabbitmq:
        host: 10.0.1.42
        port: 5672
        username: user_admin
        password: admin123%
...

---
spring:
    profiles: prod
    rabbitmq:
        host: 10.0.1.46
        port: 5672
        username: user_admin
        password: admin123%Prod
...


---
server:
    port: ${SERVER_PORT:2001}
...

---
spring:
    cloud:
        bus:
            trace:
                enabled: true
        config:
            server:
                git:
                    uri: http://118.31.22.18/p2p_group/p2p_config.git
                    cloneOnStart: true
                    force-pull: true
                    searchPaths: p2p*
                    username: cendaijun
                    password: philips1234
                health:
                    enabled: false
                    #repositories:
                        #p2p-config-server:
                            #profiles: ${SPRING_PROFILES_ACTIVE:dev}
                            #label: master
                        #p2p-config-server-branch:
                            #name: p2p-config-server
                            #profiles: ${SPRING_PROFILES_ACTIVE:dev}
                            #label: branch
    application:
        name: @project.name@${DEVLOPER_NAME:}
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
...

---
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_ADDRESS:http://eurekaserver:1111/eureka/}
        healthcheck:
            enabled: true
    instance:
        #preferIpAddress: true
        #ip-address: ${spring.cloud.client.ipAddress}
        #instance-id: ${spring.cloud.client.ipAddress}-${server.port}
        hostname: ${HOSTNAME}
        lease-expiration-duration-in-seconds: 40
        lease-renewal-interval-in-seconds: 20
        metadata-map:
            user.name: ${security.user.name}
            user.password: ${security.user.password}
            management.context-path: ${management.context-path}
        metadataMap:
            user: ${security.user.name}
            password: ${security.user.password}
        statusPageUrl: http://${HOSTNAME}:${server.port}/${management.context-path}/info
        healthCheckUrl: http://${HOSTNAME}:${server.port}/${management.context-path}/health
        secure-health-check-url: http://${HOSTNAME}:${server.port}/${management.context-path}/health
...

---
management:
    #security:
        #enabled: true
        #roles: SUPERUSER
    context-path: /manage
security:
    user:
        name: admin
        password: 123456
    basic:
        enabled: true
        path: ${management.context-path}
...
