HOSTNAME: ${spring.cloud.client.ipAddress}
---
spring:
    profiles: dev
    rabbitmq:
        host: 192.168.10.18
        port: 5672
        username: user_admin
        password: admin123%
...

---
spring:
    profiles: test
    rabbitmq:
        host: 10.0.1.42
        port: 5672
        username: user_admin
        password: admin123%
...

---
spring:
    profiles: prod
    rabbitmq:
        host: 10.0.1.46
        port: 5672
        username: user_admin
        password: admin123%Prod
...


---
server:
    port: ${SERVER_PORT:6001}
    tomcat:
        max-connections: 200
...

---
spring:
    cloud:
        bus:
            trace:
                enabled: true
    application:
        name: "@project.artifactId@"
    boot:
        admin:
            routes:
                endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
            notify:
                mail:
                    to: 66039496@qq.com
                    from: 66039496@qq.com
        #context-path: /manage
    mail:
        host: smtp.qq.com
        username: 66039496
        password: nxdgdhikcweobgbj
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
...

---
eureka:
    instance:
        #preferIpAddress: true
        ip-address: ${spring.cloud.client.ipAddress}
        hostname: ${HOSTNAME}
        metadata-map:
            user.name: ${security.user.name}
            user.password: ${security.user.password}
            management.context-path: ${management.context-path}
        statusPageUrl: http://${HOSTNAME}:${server.port}/${management.context-path}/info
        healthCheckUrl: http://${HOSTNAME}:${server.port}/${management.context-path}/health
        secure-health-check-url: http://${HOSTNAME}:${server.port}/${management.context-path}/health
        leaseRenewalIntervalInSeconds: 10
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_ADDRESS:http://eurekaserver:1111/eureka/}
...

---
management:
    #security:
        #enabled: true
        #roles: SUPERUSER
    context-path: /manage
security:
    user:
        name: admin
        password: cendaijun123!
    #basic:
        #enabled: true
        #path: ${management.context-path}
...
